import type { Config } from "tailwindcss";

const config: Config = {
    darkMode: "class",
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                "secondary-fixed": "#efdbff",
                primary: "#dbfcff",
                "inverse-surface": "#e5e1e4",
                "tertiary-fixed": "#ffd7f0",
                surface: "#131315",
                outline: "#849495",
                tertiary: "#fff3f8",
                "on-primary": "#00363a",
                "on-secondary-fixed-variant": "#6700b5",
                "tertiary-fixed-dim": "#fface8",
                "surface-bright": "#39393b",
                "primary-container": "#00f0ff",
                "surface-container-highest": "#353437",
                "primary-fixed-dim": "#00dbe9",
                "surface-container": "#201f21",
                "on-primary-fixed-variant": "#004f54",
                "on-tertiary": "#5e0053",
                "on-secondary-container": "#dcb7ff",
                "on-error-container": "#ffdad6",
                "surface-variant": "#353437",
                "on-surface-variant": "#b9cacb",
                "surface-dim": "#131315",
                "tertiary-container": "#ffcaed",
                "inverse-primary": "#006970",
                "surface-container-low": "#1c1b1d",
                "on-secondary-fixed": "#2c0051",
                "secondary-container": "#7701d0",
                "on-tertiary-container": "#ae009b",
                "error-container": "#93000a",
                "surface-tint": "#00dbe9",
                "on-background": "#e5e1e4",
                background: "#131315",
                "outline-variant": "#3b494b",
                "on-surface": "#e5e1e4",
                "secondary-fixed-dim": "#dcb8ff",
                "on-tertiary-fixed-variant": "#840076",
                "on-primary-container": "#006970",
                "on-secondary": "#480081",
                "on-error": "#690005",
                "inverse-on-surface": "#313032",
                "on-tertiary-fixed": "#3a0033",
                "surface-container-high": "#2a2a2c",
                error: "#ffb4ab",
                secondary: "#dcb8ff",
                "primary-fixed": "#7df4ff",
                "surface-container-lowest": "#0e0e10",
                "on-primary-fixed": "#002022",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {
                gutter: "24px",
                "stack-md": "24px",
                "section-padding": "120px",
                "stack-sm": "8px",
                "margin-mobile": "16px",
                "stack-lg": "64px",
                "container-max": "1280px",
            },
            fontFamily: {
                "headline-md": ["Manrope"],
                "label-caps": ["Inter"],
                "body-lg": ["Inter"],
                "label-code": ["JetBrains Mono"],
                "display-lg": ["Manrope"],
                "display-lg-mobile": ["Manrope"],
                "body-md": ["Inter"],
            },
            fontSize: {
                "headline-md": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
                "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
                "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
                "label-code": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
                "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
                "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
                "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
            },
        },
    },
    plugins: [],
};

export default config;

